Update talk slides and videos
oddbird/oddleventy pull request #254
Opened 2022-10-07 23:17 UTC by mirisuzanne

![](https://source.unsplash.com/featured/?cute,animal&eyes)

## Description
Uncomment if you want to provide a custom description.

- Added an upcoming event to /authors/miriam/
- Added a set of featured videos to /authors/miriam/
- Updated video and slide links for all of my talks

## Steps to test/reproduce
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

Mostly stuff on `/authors/miriam/`, but also scattered across a variety of talks

2022-10-07 23:21 UTC, mirisuzanne commented
![](https://github.trello.services/images/mini-trello-icon.png) [TPAC Developer Meetup](https://trello.com/c/9X3u1ukH/91-tpac-developer-meetup)

2022-10-07 23:21 UTC, mirisuzanne commented
![](https://github.trello.services/images/mini-trello-icon.png) [Event Apart](https://trello.com/c/8DnFPc4X/79-event-apart)

2022-10-08 15:22 UTC, jgerigmeyer requested changes

2022-10-08 15:22 UTC, jgerigmeyer commented on content/blog/2016/clarity.md
> +[code patterns]: http://localhost:8080/talks/code-patterns/
```suggestion
[code patterns]: /talks/code-patterns/
```

2022-10-09 00:23 UTC, jgerigmeyer approved these changes

2022-10-09 00:23 UTC, merged