Add Winging It 7 & 8
oddbird/oddleventy pull request #654
Opened 2024-07-01 20:21 UTC by SondraE

## Related Issue(s)
Add Winging It Live 7 & 8 [#653](https://github.com/oddbird/oddleventy/issues/653)

## Steps to test/reproduce
- /2024/05/16/winging-it-07/
- /2024/05/30/winging-it-08/

2024-07-02 22:01 UTC, jgerigmeyer requested changes

2024-07-02 22:01 UTC, jgerigmeyer commented on content/blog/wingingit/winging-it-08.md
> +- [Fallback options with Position-try](https://codepen.io/jamessw/pen/abrZPQY)
```suggestion
- [Fallback options with `position-try`](https://codepen.io/jamessw/pen/abrZPQY)
```

2024-07-03 19:45 UTC, SondraE commented on content/blog/wingingit/winging-it-07.md
> +- W
@stacyk Here's the PR where I could use your "What we cover" bullet points whenever you have a chance.

2024-07-03 19:56 UTC, stacyk commented on content/blog/wingingit/winging-it-07.md
> +- W
```suggestion
- What are container queries and why you should use them
- How container queries differ from media queries
- Why some layouts collapse when you add containment
- Size containment with `contain-intrinsic-size`
- Why should we avoid adding containment on root
- Why a container can't query itself
- An opt-out strategy to remove containment
```

2024-07-03 19:56 UTC, stacyk commented on content/blog/wingingit/winging-it-07.md
> +- [A Cascading Layouts Workshop June 24-26, 2024](https://www.oddbird.net/workshops/cascading-layouts/)
on the youtube description, i updated this to show only the page if you want to do the same @SondraE 

```suggestion
- [Cascading Layouts Workshop](https://www.oddbird.net/workshops/cascading-layouts/)
```

2024-07-05 17:11 UTC, SondraE commented
@jgerigmeyer Now all the content is in place. Ready for re-review.

2024-07-05 18:48 UTC, stacyk approved these changes

2024-07-05 22:11 UTC, jgerigmeyer approved these changes

2024-07-05 22:11 UTC, merged